apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gcp-csi-driver-crs
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  retryInterval: 1m
  path: ./deploy/csi-driver/gcp-compute-persistent-disk/crs
  prune: false
  sourceRef:
    kind: GitRepository
    name: tooling-stack
