apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

  - csi-driver
  - external-dns

commonLabels:
  app.tooling-stack/environment: production

patches:

  # Set production values for Cert Manager
  - patch: |
      - op: add
        path: /spec/chart/spec/valuesFiles/-
        value: ./deploy/cert-manager/operator/values-production.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: cert-manager

  # Set production values for Ingress NGINX
  - patch: |
      - op: add
        path: /spec/chart/spec/valuesFiles/-
        value: ./deploy/ingress-nginx/values-production.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: ingress-nginx
  
  # Set production values for Metrics Server
  - patch: |
      - op: add
        path: /spec/chart/spec/valuesFiles/-
        value: ./deploy/metrics-server/values-production.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: metrics-server
  
  # Set production values for Reloader
  - patch: |
      - op: add
        path: /spec/chart/spec/valuesFiles/-
        value: ./deploy/reloader/values-production.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: reloader

  # Set develop values for Snapscheduler
  - patch: |
      - op: add
        path: /spec/chart/spec/valuesFiles/-
        value: ./deploy/snapscheduler/values-production.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: snapscheduler