# Patch the Flux Kustomization for deploying the AWS EBS CSI driver for AWS Cloud Provider
---
apiVersion: reforma.prosimcorp.com/v1alpha1
kind: Patch
metadata:
  name: gcp-csi-driver-crs-kustomization
spec:
  synchronization:
    time: "5s"
  sources:
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info
      namespace: kube-system
  target:
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    name: gcp-csi-driver-crs
    namespace: flux-system
  patchType: application/json-patch+json
  template: |
    {{- $source := (index . 1) -}}
    
    {{- if eq ($source.data.provider | lower) "gcp" }}
    - op: replace
      path: /spec/suspend
      value: false
    {{- end }}
