---
apiVersion: reforma.prosimcorp.com/v1alpha1
kind: Patch
metadata:
  name: external-dns-deployment
spec:
  synchronization:
    time: "5s"
  sources:
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info
      namespace: kube-system
  target:
    apiVersion: apps/v1
    kind: Deployment
    name: external-dns
    namespace: external-dns
  patchType: application/json-patch+json
  template: |
    {{- $source := (index . 1) -}}
    {{- $target := (index . 0) -}}

    {{/* Get the original flags of the target */}}
    {{- $target_args := list -}}

    {{/* Flags for all the cloud providers */}}
    {{- $target_args = append $target_args "--log-level=info" -}}
    {{- $target_args = append $target_args "--log-format=json" -}}
    {{- $target_args = append $target_args "--source=ingress" -}}
    {{- $target_args = append $target_args "--source=service" -}}
    {{- $target_args = append $target_args "--interval=1m" -}}
    {{- $target_args = append $target_args (cat "--txt-owner-id=" $source.data.name | nospace) -}}

    {{/* Flags for AWS only */}}
    {{- if eq ($source.data.provider | lower) "aws" }}
    {{- $target_args = append $target_args "--provider=aws" -}}
    {{- $target_args = append $target_args "--aws-zone-type=public" -}}
    {{- end }}

    {{/* Flags for GCP only */}}
    {{- if eq ($source.data.provider | lower) "gcp" }}
    {{- $target_args = append $target_args "--provider=google" -}}
    {{- $target_args = append $target_args (cat "--google-project=" $source.data.account | nospace) -}}
    {{- end }}

    - op: replace
      path: /spec/template/spec/containers/0/args
      value:        
        {{- $target_args | uniq | toYaml | nindent 4 -}}
