---
apiVersion: reforma.prosimcorp.com/v1alpha1
kind: Patch
metadata:
  name: external-dns-service-account
spec:
  synchronization:
    time: "5s"
  sources:
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info
      namespace: kube-system
  target:
    apiVersion: v1
    kind: ServiceAccount
    name: external-dns
    namespace: external-dns
  patchType: application/merge-patch+json
  template: |
    {{- $source := (index . 1) -}}
    metadata:
      annotations:          
        {{- if eq ($source.data.provider | lower) "aws" }}
        eks.amazonaws.com/role-arn: "arn:aws:iam::{{- $source.data.account -}}:role/{{- $source.data.name -}}-external-dns"
        {{- end }}

        {{- if eq ($source.data.provider | lower) "gcp" }}
        iam.gke.io/gcp-service-account: "{{- $source.data.name -}}-external-dns@{{- $source.data.account -}}.iam.gserviceaccount.com"
        {{ end }}
