---
# Deploy External Secrets CRs
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-crs
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./deploy/external-secrets/crs
  prune: true
  sourceRef:
    kind: GitRepository
    name: tooling-stack
