apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reforma

resources:
  - https://github.com/prosimcorp/reforma//deploy/?ref=v0.1.1

  # Add your custom resources
  - clusterRole-reforma-custom-resources.yaml
  - clusterRoleBinding-reforma-custom-resources.yaml
