apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  # Override Release name to avoid the pattern Namespace-Release
  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.HelmRelease
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  interval: 5m
  chart:
    spec:
      chart: ./deploy/ingress-nginx
      sourceRef:
        kind: GitRepository
        name: tooling-stack
        namespace: flux-system
      valuesFiles:
        - ./deploy/ingress-nginx/values.yaml

  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
  install:
    createNamespace: true
    remediation: &remediation
      retries: 10
      remediateLastFailure: true
  upgrade:
    remediation: *remediation
