apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: replika
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  retryInterval: 1m
  path: ./deploy/replika
  prune: false
  sourceRef:
    kind: GitRepository
    name: tooling-stack
    namespace: flux-system
