apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws-csi-driver
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./deploy/csi-driver/aws-ebs/controller
  prune: false
  sourceRef:
    kind: GitRepository
    name: tooling-stack
