apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-snapshotter-crs
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  retryInterval: 1m
  path: ./deploy/external-snapshotter/crs
  prune: true
  sourceRef:
    kind: GitRepository
    name: tooling-stack
    namespace: flux-system
