apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - patch-aws-csi-driver-controller-service-account.yaml
  - patch-aws-csi-driver-node-service-account.yaml
  - storageClass-csi-block.yaml
