# Patch the Flux Kustomization for deploying the AWS EBS CSI driver for AWS Cloud Provider
---
apiVersion: reforma.prosimcorp.com/v1alpha1
kind: Patch
metadata:
  name: aws-csi-driver-controller-service-account
spec:
  synchronization:
    time: "5s"
  sources:
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info
      namespace: kube-system
  target:
    apiVersion: v1
    kind: ServiceAccount
    name: ebs-csi-controller-sa
    namespace: kube-system
  patchType: application/merge-patch+json
  template: |
    {{- $source := (index . 1) -}}
    metadata:
      annotations:          
        eks.amazonaws.com/role-arn: "arn:aws:iam::{{- $source.data.account -}}:role/{{- $source.data.name -}}-csi-driver"
