apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: do-csi-driver-crs
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./deploy/csi-driver/do-block-storage/crs
  prune: false
  sourceRef:
    kind: GitRepository
    name: tooling-stack
