apiVersion: reforma.prosimcorp.com/v1alpha1
kind: Patch
metadata:
  name: external-dns-deployment-common
spec:
  synchronization:
    time: "1m"
  sources:
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info
      namespace: kube-system
  target:
    apiVersion: apps/v1
    kind: Deployment
    name: external-dns
    namespace: external-dns
  patchType: application/json-patch+json
  template: |
    {{- $source := (index . 1) -}}
    {{- $target := (index . 0) -}}

    {{/* Get the original flags of the target */}}
    {{- $old_target_args := index $target.spec.template.spec.containers 0 -}}
    {{- $old_target_args := $old_target_args.args -}}

    {{/* Craft new flags for the target */}}
    {{- $target_args := list -}}

    {{- $target_args = append $target_args "--log-level=info" -}}
    {{- $target_args = append $target_args "--log-format=json" -}}
    {{- $target_args = append $target_args "--source=ingress" -}}
    {{- $target_args = append $target_args "--source=service" -}}
    {{- $target_args = append $target_args "--interval=1m" -}}
    {{- $target_args = append $target_args (cat "--txt-owner-id=" $source.data.name | nospace) -}}

    {{/* Check if all flags are already present */}}
    {{- $counter := int 0 -}}
    {{- range $target_args -}}
      {{- if has . $old_target_args -}}
        {{- $counter = add $counter 1 -}}
      {{- end -}}
    {{- end -}}

    {{- if ne $counter (len $target_args) -}}
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
        {{- $target_args | uniq | toYaml | nindent 4 -}}
    {{- end -}}
